config/routes.rb
Rails.application.routes.draw do
  get 'logs/:id/new', to: 'logs#new', as: :new_log_entry
  resources :logs

  devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      sessions: 'users/sessions'
  }

  resources :users, only: [:show, :update]

  get '/welcome', to: 'users#welcome', as: :welcome

  authenticated :user do
    root 'logs#index', as: :authenticated_root
  end

  root to: "static_pages#index"
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :activity
  belongs_to :activity_intensity
  belongs_to :user
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_if_user_miss_props
  before_action :set_log_entry, only: [:show, :edit, :update, :destroy]

  def index
    @logs = Log.all.includes(:activity, :activity_intensity).order(id: :desc).where(user_id: current_user.id)
    @activities = Activity.all.order(:id)
    @user = current_user
  end

  def show
  end

  def edit
    @activity = Activity.find(@log.activity_id)
  end

  def new
    @log = Log.new
    @activity = Activity.find(params[:id])
  end

  def create
    @log = Log.new(log_params)
    @log.user = current_user
    @activity = Activity.find(log_params[:activity_id])

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log entry was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Log entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Log entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_log_entry
    @log = Log.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def log_params
    params.require(:log).permit(:duration, :activity_id, :activity_intensity_id, :user_id, :comment, :feeling)
  end

end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= form_with(model: log, local: true) do |f| %>
  <% if log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
        <% log.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h3>How do you feel about your session?</h3>
  <div class="form-check form-check-radio form-check-inline">
    <label class="form-check-label">
      <%= f.radio_button :feeling, 'i1', {class: 'form-check-input', id: 'inlineRadio1'} %> <i id="i1" class="material-icons radio display-2">sentiment_very_dissatisfied</i>
    </label>
  </div>
  <div class="form-check form-check-radio form-check-inline">
    <label class="form-check-label">
      <%= f.radio_button :feeling, 'i2', {class: 'form-check-input', id: 'inlineRadio2'} %> <i id="i2" class="material-icons radio display-2">sentiment_dissatisfied</i>
    </label>
  </div>
  <div class="form-check form-check-radio form-check-inline">
    <label class="form-check-label">
      <%= f.radio_button :feeling, 'i3', {class: 'form-check-input', id: 'inlineRadio3'} %> <i id="i3" class="material-icons radio display-2">sentiment_neutral</i>
    </label>
  </div>
  <div class="form-check form-check-radio form-check-inline">
    <label class="form-check-label">
      <%= f.radio_button :feeling, 'i4', {class: 'form-check-input', id: 'inlineRadio4'} %> <i id="i4" class="material-icons radio display-2">sentiment_satisfied</i>
    </label>
  </div>
  <div class="form-check form-check-radio form-check-inline">
    <label class="form-check-label">
      <%= f.radio_button :feeling, 'i5', {class: 'form-check-input', id: 'inlineRadio5'} %> <i id="i5" class="material-icons radio display-2">sentiment_very_satisfied</i>
    </label>
  </div>

  <div class="row">
    <div class="col-8 mx-auto text-center">
      <div class="form-group">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="material-icons">alarm</i></span>
          </div>
          <%= f.number_field :duration, within: 1..600, required: true, class: 'form-control', placeholder: 'Duration in minutes' %>
        </div>
      </div>

      <div class="form-group">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="material-icons">stars</i></span>
          </div>
          <%= f.collection_select(:activity_intensity_id, @activity.activity_intensities, :id, :title, {prompt: 'Session\'s difficulty'}, {class:'form-control', required: true}) %>
        </div>
      </div>

      <div class="form-group">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="material-icons">comment</i></span>
          </div>
          <%= f.text_area :comment, required: true, class: 'form-control',rows:3, placeholder: 'Add a comment about your session' %>
        </div>
      </div>
    </div>
  </div>
  <%= f.hidden_field :activity_id, value:@activity.id %>

  <div class="actions text-center">
    <%= f.submit "Submit entry", class:'btn btn-primary' %>
  </div>
<% end %>

app/views/logs/_show.html.erb
<div class="row">
  <div class="col-md-8 ml-auto mr-auto">
    <div class="card card-transparent">
      <div class="card-header card-header-rose text-center p-0">
        <h2>
          <i class="icons8-<%= @log.activity.icon %> display-1 float-left"></i>
          <%= @log.activity.name %> session
        </h2>
        <% met = calculate_calories_from_met(@log.activity_intensity.met, @log.user.weight, @log.duration) %>
        <h3><%= @log.activity_intensity.title %> · <%= @log.duration %>mn · <%= met %> kcal</h3>
      </div>
      <div class="card-body pl-5 pr-4 pt-4 pb-0">
        <div class="media-area">
          <div class="media">
            <a class="float-left" href="#pablo">
              <div class="avatar">
                <img class="media-object" src="<%= @log.user.avatar %>" alt="...">
              </div>
            </a>
            <div class="media-body">
              <h4 class="media-heading" style="font-family:inherit !important;">
                <%= @log.user.name %> <i class="material-icons"><%= feeling_icon(@log.feeling) %></i>
                <small>· <%= @log.created_at.strftime("%B %e, %Y") %></small>
              </h4>
              <p><%= simple_format(@log.comment) %></p>
              <div class="media-footer">
                <a href="" class="btn btn-primary btn-link float-right" rel="tooltip" title="" data-original-title="Just a mockup">
                  <i class="material-icons">comment</i> Comment
                </a>
                <a href="" class="btn btn-danger btn-link float-right">
                  <i class="material-icons">favorite</i> 0
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/logs/edit.html.erb
<div class="row">
  <div class="col-md-8 ml-auto mr-auto px-5">
    <div class="card card-transparent">
      <div class="card-header card-header-rose text-center">
        <h3 class="mt-0 mb-1"><i class="icons8-<%= @activity.icon %>" style="font-size:5rem"></i><br />Edit my <%= @activity.name.downcase %> session</h3>
      </div>
      <div class="card-body px-5 pb-4">
        <div class="text-center">
          <%= render 'form', log: @log%>
        </div>

        <%= link_to 'Show', @log %> |
        <%= link_to 'Back', logs_path %>
      </div>
    </div>
  </div>
</div>

app/views/logs/index.html.erb
<div class="row">
  <div class="col-md-8 col-sm-12 px-0">
    <h3>Daily logs</h3>
    <% if @logs.empty? %>
      <div class="row">
        <div class="col-12 ml-auto mr-auto">
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Oops!</strong><br />
            It looks like you don't have logged any activities yet!
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
      </div>
    <% else %>
      <table class="table table-striped table-hover table-sm">
        <thead>
        <tr>
          <th>Date</th>
          <th>Feel</th>
          <th>Name</th>
          <th>Duration</th>
          <th>Intensity</th>
          <th>Calories</th>
          <th colspan="3">Actions</th>
        </tr>
        </thead>

        <tbody>
        <% @logs.each do |log| %>
          <% met = calculate_calories_from_met(log.activity_intensity.met, @user.weight, log.duration) %>
          <tr>
            <td><%= log.created_at.strftime("%d/%m") %></td>
            <td><i id="<%= log.feeling %>" class="material-icons forced"><%= feeling_icon(log.feeling) %></i></td>
            <td><%= log.activity.name %></td>
            <td><%= log.duration %>mn</td>
            <td><%= log.activity_intensity.title %></td>
            <td><%= met %></td>
            <td class="td-actions px-0">
              <%= link_to log do %>
                <button type="button" rel="tooltip" class="btn btn-info btn-sm p-1 m-0">
                  <i class="material-icons">search</i>
                </button>
              <% end %>
            </td>
            <td class="td-actions px-0">
              <%= link_to edit_log_path(log) do %>
                <button type="button" rel="tooltip" class="btn btn-success btn-sm btn-sm p-1 m-0">
                  <i class="material-icons">edit</i>
                </button>
              <% end %>
            </td>
            <td class="td-actions px-0">
              <%= link_to log, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <button type="button" rel="tooltip" class="btn btn-danger btn-sm btn-sm p-1 m-0">
                  <i class="material-icons">close</i>
                </button>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% end %>

  </div>
  <div class="col-md-4 col-sm-12 text-right p-0">
    <h3>Add a log entry</h3>
    <% i = 0 %>
    <div class="btn-group-vertical m-0" role="group">
      <% @activities.each do |activity| %>
        <% i += 1 %>
        <%= link_to new_log_entry_path(activity.id), class: 'btn btn-primary mb-1' do %>
          <i class="icons8-<%= activity.icon %> display-2"></i><br />
          <%= activity.name %>
        <% end %>
        <% if i == 4 || i == 8 %>
          </div>
          <div class="btn-group-vertical" role="group">
        <% end %>
      <% end %>
      </div>
  </div>
</div>

app/views/logs/new.html.erb
<div class="row">
  <div class="col-md-8 ml-auto mr-auto px-5">
    <div class="card card-transparent">
      <div class="card-header card-header-rose text-center">
        <h3 class="mt-0 mb-1"><i class="icons8-<%= @activity.icon %>" style="font-size:5rem"></i><br />New <%= @activity.name.downcase %> session</h3>
      </div>
      <div class="card-body px-5 pb-4">
        <div class="text-center">
          <%= render 'form', log: @log%>
        </div>

        <%= link_to 'Back', logs_path %>
      </div>
    </div>
  </div>
</div>

app/views/logs/show.html.erb
<%= render 'logs/show' %>