config/routes.rb
Rails.application.routes.draw do
  get 'logs/:id/new', to: 'logs#new', as: :new_log_entry
  resources :logs

  devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      sessions: 'users/sessions'
  }

  resources :users, only: [:show, :update]

  get '/welcome', to: 'users#welcome', as: :welcome

  authenticated :user do
    root 'logs#index', as: :authenticated_root
  end

  root to: "static_pages#index"
end

app/views/layouts/_footer.html.erb
<nav class="footer mb-0 p-0 ">
  <div class="container justify-content-center">
    <% if(user_session) %>
      <%= link_to "Dashboard", logs_path %>
    <% end %>
    &copy; 2018 Move&Groove - All Rights Reserved - Franck Boudraa
  </div>
</nav>

app/views/layouts/_header.html.erb
<% if(user_session) %>
  <%= render("layouts/navbar_logged") %>
<% else %>
  <%= render("layouts/navbar_not_logged") %>
<% end %>

app/views/layouts/_navbar_logged.html.erb
<% if (current_user.avatar.nil?) then avatar = 'camp' else avatar = current_user.avatar end %>
<nav class="navbar navbar-light navbar-expand-lg">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-translate">
      <a class="navbar-brand" style="font-size:1.5rem !important;" href="/">move&groove</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto">
        <% if current_user.name.nil? %>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Dashboard", logs_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to '', class: 'nav-link' do %>
            <i class="material-icons">forum</i>
          <% end %>
        </li>
          <li class="nav-item">
            <%= link_to '', class: 'nav-link' do %>
              <i class="material-icons">notifications_none</i>
            <% end %>
          </li>
          <li class="dropdown nav-item">
            <%= link_to user_path(current_user), {:class => 'profile-photo dropdown-toggle nav-link', "data-toggle" => 'dropdown'} do %>
              <div class="profile-photo-small">
                <img src="<%= avatar %>" alt="Circle Image" class="rounded-circle img-fluid">
              </div>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right">
              <h6 class="dropdown-header"><%= current_user.name %></h6>
              <%= link_to "My profile", user_path(current_user), class:'dropdown-item' %>
              <%= link_to "Preferences", edit_user_registration_path, class:'dropdown-item' %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class:'dropdown-item' %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-->
</nav>

app/views/layouts/_navbar_not_logged.html.erb
<nav class="navbar navbar-transparent navbar-expand-lg">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-translate">
      <a class="navbar-brand" href="/">move&groove</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item mr-1">
          <%= link_to new_user_session_path, class:'btn btn-secondary' do %>
            <%= icon('fas', 'sign-in-alt', 'Login') %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_registration_path, class:'btn btn-primary' do %>
            <%= icon('fas', 'user-plus', 'Register') %>
          <% end %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MoveGroove</title>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<% if !current_user && controller_name != 'users' && action_name != 'show' %>
  <% body_class = 'homepage-bg' # Set image background on public pages %>
<% else %>
  <% body_class = 'dash-bg' # No image background on private pages %>
<% end %>
<body class="<%= body_class %>" >
<%= render('layouts/header') %>
<div class="container mb-5">
  <% if(notice) %>
    <div class="row">
      <div class="col-6 ml-auto mr-auto">
        <div class="alert alert-info alert-dismissible fade show" role="alert">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    </div>
  <% end %>

  <% if(alert) %>
    <div class="row">
      <div class="col-6 ml-auto mr-auto">
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= alert %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    </div>
  <% end %>
  <%= yield %>
</div>
<%= render('layouts/footer') %>
</body>
</html>